### ISSUE TITLE
Clarify instructions - add names for each language

### ISSUE THREAD

**Issue by adammendoza** [bluzi/name-db#13]
I noticed that pull requests are given for only the original language. I'm not sure if it's due to misunderstanding the intent of the list that you want translation of each name into all languages.

**Comment by bluzi** [comment]
Hi @adammendoza!

I guess that most of our contributors don't know how to spell their name in other languages, that's acceptable :) 
If you feel like the documentation is not clear enough, feel free to modify it and create a PR. I'll gladly merge it :)
