### ISSUE TITLE
Fix mocha tests

### ISSUE THREAD

**Issue by bluzi** [bluzi/name-db#146]
The "done" is being called more than once in some cases

**Comment by ThrowsException** [comment]
How do you know its being called more than once?

**Comment by ThrowsException** [comment]
Also is there any reason to actually use the `done` callback. I think all of these tests could be written without it.

**Comment by bluzi** [comment]
hi @ThrowsException, here's an example to this behavior: https://travis-ci.org/bluzi/name-db/builds/292854941

as to the `done` - if you think you can make a better implementation without it, i'll be glad to merge it.

**Comment by jwcnewton** [comment]
@ThrowsException 

> Also is there any reason to actually use the done callback

In the scenario that you want to manually fail a test you do need them

**Comment by jwcnewton** [comment]
#148
