### ISSUE TITLE
Missing languages in the ISO 639-3 language codes.

### ISSUE THREAD

**Issue by adammendoza** [bluzi/name-db#16]
Some languages seem to be missing from the list in https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

For example, Hmong, 

Also there is a single Chinese vs Chinese Simplified and Chinese Traditional

- Adam

**Comment by bluzi** [comment]
Can you suggest a better standard?

**Comment by bluzi** [comment]
Here's a better list of ISO-639-3 language codes. I checked and it contains the language you were looking for:
https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes
