### ISSUE TITLE
Create a script to scrape names

### ISSUE THREAD

**Issue by haloboy777** [bluzi/name-db#199]
I was thinking if it's allowed to just find a website with names and scrape it all and then using another script find translations of the name using Google translate?

I'm mean that would be so fast to grow the database.. instead of waiting for someone to commit a PR.

**Comment by bluzi** [comment]
Hey @haloboy777,

There's already a discussion about such name scraper, started by @EmilLuta.
I invite you to participate: 
https://github.com/bluzi/name-db/issues/95

**Comment by haloboy777** [comment]
okay sure..
