### ISSUE TITLE
Add tests 

### ISSUE THREAD

**Issue by bluzi** [bluzi/name-db#2]
#- Add your favorite test engine to the project
- Write some test cases (Validate the JSON, validate the encoding, [enforce the specs](https://github.com/bluzi/name-db/blob/master/README.md), etc)
- Add `package.json` and add `test` script. (So that `npm run test` will run the tests)

**Comment by chrisf** [comment]
Mind if I work on this?

**Comment by bluzi** [comment]
it's yours :)

**Comment by bluzi** [comment]
thanks @chrisf!
