### ISSUE TITLE
Multiple possible translations

### ISSUE THREAD

**Issue by CrowsVeldt** [bluzi/name-db#206]
What should I do in the case of a name with multiple possible translations? For example:
"Jonathon" can be either "יונתן" or "יהונתן" in Hebrew.

I can think of a few possibilities

1. "code": "name/otherName"
~~2. "code": "name"
    "code": "otherName"~~
1. "code" ["name", "otherName"]

What do you think?

**Comment by CrowsVeldt** [comment]
I just realized that option #2 won't work, since the code is the key of the pair.

**Comment by bluzi** [comment]
Hey @CrowsVeldt,

The current solution is using an alias. Using your example, I'd translate *Jonathon* to *ג'ונתן*, and add *Yonatan* and *Yhonatan* in different files, and add their translations. (*יונתן* and *יהונתן*)

Does that answer your question?

**Comment by CrowsVeldt** [comment]
Yeah, thanks!

**Comment by bluzi** [comment]
Great :) 
BTW, your PR conflicts with the master branch, so it'll take some time for me to merge it, but don't worry about it.

**Comment by CrowsVeldt** [comment]
Oh, I just saw that it was marked conflicted so I fixed the conflicts. I hope that's okay!
