### ISSUE TITLE
Names and nicknames/derivations

### ISSUE THREAD

**Issue by djphan** [bluzi/name-db#27]
Hi, I was curious if as a feature request it would be cool to include common derivations of a name.

For example Richard can be shortened to Dick
Or Daniel is shortened to Dan or can be Danielle (female form).

What are your thoughts?

**Comment by bluzi** [comment]
Hi @djphan!
I definitely agree. I just wonder if we should translate derivations as well. What do you think?

**Comment by chrisf** [comment]
Maybe the derivations can be a reference to another name object?

So for the given example we could have:

```
{
    "name": "Richard",
    "meaning": "...",
    "derivations": "Dick",
    "translations": { ... },
},
{
    "name": "Dick",
    // etc
}
```

**Comment by bluzi** [comment]
done
