### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by bluzi** [bluzi/name-db#40]
Add the following tests to the existing test cases: 
- Test for duplicate names - Solved #78
- Test for good indention (compare the JSON as plain text to the result of `JSON.stringify(json, null, 4)` or something like that)
- Test all language codes against a ISO-639-3 language codes, to make sure they all valid
- Test if `name` has non-english characters
- Make sure the translations object does not contain English (`eng`) translation - Solved #66 
- etc

These are just ideas, feel free to suggest more tests here, or just create a PR.

**Comment by maxtotterman** [comment]
I could take a look at this one.

**Comment by bluzi** [comment]
@chrisf, maybe you want to take some of these? :)

**Comment by chrisf** [comment]
@bluzi sure I'll take a few when I'm done with work and school for the day

**Comment by bluzi** [comment]
awesome
