### ISSUE TITLE
English translation should not fail the tests

### ISSUE THREAD

**Issue by arminkhoshbin** [bluzi/name-db#439]
I've realised that English translations (`eng` ISO code) for names fail the test. This is not ideal since there are names which originates from other countries but they may have English meanings.

Has there been any reasoning behind this @bluzi ?
PR #244 is a good example.

**Comment by bluzi** [comment]
Hi @arminkhoshbin,

The goal of the project is not to translate meanings, it's to spell the name in different languages. The `name` field should contain the English spelling, and the `translations` should contain a map of language code and the spelling of that name in this language.

Does this answer your question? What do you think about that?

**Comment by roastchicken** [comment]
@bluzi, isn't the example in [your comment](https://github.com/bluzi/name-db/issues/87#issuecomment-339377555) a file with a non-English spelling in the `name` field? I think this demonstrates an issue: if we only allow English spellings to have their own files, we prevent non-English aliases that don't directly translate to an English name from being added.

Maybe that's what you want, if it's meant to be a database of primarily English names.

**Comment by bluzi** [comment]
@roastchicken 
I want the collection to contain names from all origins, that's for sure.
My vision is having all kind of names, translated to all languages.

For standardization reasons, I thought it'll be best if the title for each name will be its English translation, and each name will have an array of different spellings.

You can add names from other origins (like I did with `yoni`), but you can't add names spelled in languages other then English (for example, you can't add the name `יוני`, which is Hebrew for `yoni`)
So the format in the comment you attached is valid, you can add an Hebrew name, but it should be spelled in English, and it may have translations to any language you want.

**Comment by arminkhoshbin** [comment]
So just to confirm @bluzi you can have names from other origins but they need to be spelled in English and you can have translations to any language including English? If that's the case then the translation test needs to be updated because having an English translation will fail it.

**Comment by roastchicken** [comment]
@bluzi I guess I misinterpreted Yoni. I thought that spelling was not the Engish spelling. I can't think of an example, and maybe no such names exist, but I have a feeling there are names that don't have a direct match in English. But I guess that isn't exactly related to this issue, because such names wouldn't have English translations either.

@arminkhoshbin if all names are spelled in English in the `name` field, what would be the point in having an English translation? Wouldn't that just be duplicate data?

**Comment by arminkhoshbin** [comment]
Not necessarily @roastchicken. Take the name `Santiago` or other aliases of it like Diego as an example. It is of Spanish origin but when translated to English it's James. As a matter of fact the name James is a really common name with many forms in other languages.

https://en.wikipedia.org/wiki/Santiago_%28name%29
https://spanish.stackexchange.com/questions/4588/why-is-santiago-the-equivalent-of-james

**Comment by roastchicken** [comment]
@arminkhoshbin could you show me an example file where you would need an English translation? Or are you refuting my first point? I'm having trouble imagining a scenario where an English translation would be necessarily or helpful.

**Comment by arminkhoshbin** [comment]
@roastchicken https://github.com/bluzi/name-db/pull/244/files

**Comment by roastchicken** [comment]
@arminkhoshbin but @bluzi said the `name` field should be in English. So that file would be something like this:

```
{
    "name": "james", 
    "meaning": "the one that changes",
    "aliases": ["jacob", "jacobo", "diego"],
    "translations": {
        "spa": "santiago" 
    }
}
```

**Comment by arminkhoshbin** [comment]
Thanks @roastchicken. I think you're right. In other words if any name has an English translation then the translation can have its own JSON file. Closing this issue now.

**Comment by bluzi** [comment]
@arminkhoshbin that's correct. The English translation is the `name` property, and if a name has more than one English translation, it should have its own file.

Are you completely satisfied with this behavior? If you have any comments, please let me know

**Comment by arminkhoshbin** [comment]
Yes. All sorted now @bluzi 👍

**Comment by bluzi** [comment]
Good :) 

Feel free to create more discussions like this one, I feel like it's good to talk about this kind of stuff.

Also, if you feel like the documentation could be more clear about this matter, feel free to improve it if you want to 

@arminkhoshbin @roastchicken
